//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 4/22/2016 11:26:39 AM
namespace ConsoleApplication3.ServiceReference1
{
    
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    public partial class Container : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Container(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "od0", "ConsoleApplication3.ServiceReference1");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("ConsoleApplication3.ServiceReference1", global::System.StringComparison.Ordinal))
            {
                return string.Concat("od0.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for titles in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<title> titles
        {
            get
            {
                if ((this._titles == null))
                {
                    this._titles = base.CreateQuery<title>("titles");
                }
                return this._titles;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<title> _titles;
        /// <summary>
        /// There are no comments for titles in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddTotitles(title title)
        {
            base.AddObject("titles", title);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = @"<edmx:Edmx Version=""1.0"" xmlns:edmx=""http://schemas.microsoft.com/ado/2007/06/edmx""><edmx:DataServices m:DataServiceVersion=""3.0"" m:MaxDataServiceVersion=""3.0"" xmlns:m=""http://schemas.microsoft.com/ado/2007/08/dataservices/metadata""><Schema Namespace=""od0"" xmlns=""http://schemas.microsoft.com/ado/2009/11/edm""><EntityType Name=""title""><Key><PropertyRef Name=""title_id"" /></Key><Property Name=""title_id"" Type=""Edm.String"" Nullable=""false"" /><Property Name=""title1"" Type=""Edm.String"" /><Property Name=""type"" Type=""Edm.String"" /><Property Name=""pub_id"" Type=""Edm.String"" /><Property Name=""price"" Type=""Edm.Decimal"" /><Property Name=""advance"" Type=""Edm.Decimal"" /><Property Name=""royalty"" Type=""Edm.Int32"" /><Property Name=""ytd_sales"" Type=""Edm.Int32"" /><Property Name=""pubdate"" Type=""Edm.DateTime"" Nullable=""false"" /></EntityType></Schema><Schema Namespace=""Default"" xmlns=""http://schemas.microsoft.com/ado/2009/11/edm""><EntityContainer Name=""Container"" m:IsDefaultEntityContainer=""true""><EntitySet Name=""titles"" EntityType=""od0.title"" /></EntityContainer></Schema></edmx:DataServices></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for od0.title in the schema.
    /// </summary>
    /// <KeyProperties>
    /// title_id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("titles")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("title_id")]
    public partial class title : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new title object.
        /// </summary>
        /// <param name="title_id">Initial value of title_id.</param>
        /// <param name="pubdate">Initial value of pubdate.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static title Createtitle(string title_id, global::System.DateTime pubdate)
        {
            title title = new title();
            title.title_id = title_id;
            title.pubdate = pubdate;
            return title;
        }
        /// <summary>
        /// There are no comments for Property title_id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string title_id
        {
            get
            {
                return this._title_id;
            }
            set
            {
                this.Ontitle_idChanging(value);
                this._title_id = value;
                this.Ontitle_idChanged();
                this.OnPropertyChanged("title_id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _title_id;
        partial void Ontitle_idChanging(string value);
        partial void Ontitle_idChanged();
        /// <summary>
        /// There are no comments for Property title1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string title1
        {
            get
            {
                return this._title1;
            }
            set
            {
                this.Ontitle1Changing(value);
                this._title1 = value;
                this.Ontitle1Changed();
                this.OnPropertyChanged("title1");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _title1;
        partial void Ontitle1Changing(string value);
        partial void Ontitle1Changed();
        /// <summary>
        /// There are no comments for Property type in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string type
        {
            get
            {
                return this._type;
            }
            set
            {
                this.OntypeChanging(value);
                this._type = value;
                this.OntypeChanged();
                this.OnPropertyChanged("type");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _type;
        partial void OntypeChanging(string value);
        partial void OntypeChanged();
        /// <summary>
        /// There are no comments for Property pub_id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string pub_id
        {
            get
            {
                return this._pub_id;
            }
            set
            {
                this.Onpub_idChanging(value);
                this._pub_id = value;
                this.Onpub_idChanged();
                this.OnPropertyChanged("pub_id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _pub_id;
        partial void Onpub_idChanging(string value);
        partial void Onpub_idChanged();
        /// <summary>
        /// There are no comments for Property price in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> price
        {
            get
            {
                return this._price;
            }
            set
            {
                this.OnpriceChanging(value);
                this._price = value;
                this.OnpriceChanged();
                this.OnPropertyChanged("price");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _price;
        partial void OnpriceChanging(global::System.Nullable<decimal> value);
        partial void OnpriceChanged();
        /// <summary>
        /// There are no comments for Property advance in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> advance
        {
            get
            {
                return this._advance;
            }
            set
            {
                this.OnadvanceChanging(value);
                this._advance = value;
                this.OnadvanceChanged();
                this.OnPropertyChanged("advance");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _advance;
        partial void OnadvanceChanging(global::System.Nullable<decimal> value);
        partial void OnadvanceChanged();
        /// <summary>
        /// There are no comments for Property royalty in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> royalty
        {
            get
            {
                return this._royalty;
            }
            set
            {
                this.OnroyaltyChanging(value);
                this._royalty = value;
                this.OnroyaltyChanged();
                this.OnPropertyChanged("royalty");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _royalty;
        partial void OnroyaltyChanging(global::System.Nullable<int> value);
        partial void OnroyaltyChanged();
        /// <summary>
        /// There are no comments for Property ytd_sales in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> ytd_sales
        {
            get
            {
                return this._ytd_sales;
            }
            set
            {
                this.Onytd_salesChanging(value);
                this._ytd_sales = value;
                this.Onytd_salesChanged();
                this.OnPropertyChanged("ytd_sales");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _ytd_sales;
        partial void Onytd_salesChanging(global::System.Nullable<int> value);
        partial void Onytd_salesChanged();
        /// <summary>
        /// There are no comments for Property pubdate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime pubdate
        {
            get
            {
                return this._pubdate;
            }
            set
            {
                this.OnpubdateChanging(value);
                this._pubdate = value;
                this.OnpubdateChanged();
                this.OnPropertyChanged("pubdate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _pubdate;
        partial void OnpubdateChanging(global::System.DateTime value);
        partial void OnpubdateChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
